name: CI/CD Farmacias

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend-farmacias, usuarios-servicio]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        if: matrix.service != 'frontend-farmacias'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Set up Node.js
        if: matrix.service == 'frontend-farmacias'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & test
        run: |
          cd ${{ matrix.service }}
          if [ "${{ matrix.service }}" = "frontend-farmacias" ]; then
            npm ci
          else
            ./mvnw clean package
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
